project:
  type: book

book:
  title: "Notes on Sheldon Natenberg's Options Volatility and Pricing"
  author: "Prabhav Shetty"
  date: "6/9/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



